# Generated by Django 3.0.7 on 2020-06-29 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banter', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='imagelink',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
